version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # ext services port range
      - "127.0.0.1:53:53"                # DNS config
      - "127.0.0.1:53:53/udp"            # DNS config
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-2
      - HOST_TMP_FOLDER=/tmp/localstack
      - ENFORCE_IAM=1
    volumes:
      - ./tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-entrypoint.sh:/etc/localstack/init/ready.d/init-aws.sh
