version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: tribble
      POSTGRES_USER: laughing_tribble
      POSTGRES_PASSWORD: PwdSecret123!
    ports:
      - 5432:5432
    volumes:
      - ./tmp:/var/lib/postgresql/data
